version: "3.8" # docker-compose --version

services:
  dockerize_nodejs_api_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: dockerize_nodejs_api:v1 # image
    working_dir: /var/www/html
    container_name: dockerize_nodejs_api_container1
    env_file:
      - ./app/.env
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/html
