version: "3.3" # docker-compose --version
services:
  dockerize_nodejs_api: # image
    build: ./app
    image: dockerize_nodejs_api:v1
    working_dir: /dockerize_nodejs_api
    container_name: dockerize_nodejs_api_c
    ports:
      - '80:80'
    volumes:
      - ./app:/dockerize_nodejs_api
      - ./app/node_modules:/dockerize_nodejs_api/node_modules
