name: CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd app
          npm install

  cd:
    runs-on: ubuntu-latest
    needs: ci
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.XTOKEN }}
        timeout-minutes: 5

      - name: Build app Docker image
        run: |
          cd app
          docker build -t dockerize_nodejs_api:v1 .
        timeout-minutes: 5

      - name: Push app Docker image to Docker Hub
        run: |
          docker tag dockerize_nodejs_api:v1 ${{ secrets.DOCKER_USERNAME }}/dockerize_nodejs_api:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerize_nodejs_api:v1
        timeout-minutes: 5

      - name: Push app Docker image to GHCR
        run: |
          docker tag dockerize_nodejs_api:v1 ghcr.io/${{ github.repository_owner }}/dockerize_nodejs_api:v1
          docker push ghcr.io/${{ github.repository_owner }}/dockerize_nodejs_api:v1
        timeout-minutes: 5
