name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 5

      - name: Build Docker image
        run: |
          cd app
          docker build -t dockerize_nodejs_api:v1 .
        timeout-minutes: 5

      - name: Push Docker image
        run: |
          docker tag dockerize_nodejs_api:v1 ${{ secrets.DOCKER_USERNAME }}/dockerize_nodejs_api:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerize_nodejs_api:v1
        timeout-minutes: 5
